# Generated by Django 4.2.8 on 2023-12-16 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_userlearnedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.ManyToManyField(related_name='correct_for', to='study.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answers', models.ManyToManyField(related_name='chosen_by_user', to='study.answer')),
            ],
        ),
    ]
