# Generated by Django 4.2.8 on 2023-12-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_usertestscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
