# Generated by Django 4.2.8 on 2023-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_word_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='learning_method',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
