# Generated by Django 4.2.8 on 2023-12-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_question_group_word_learning_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
