# Generated by Django 4.2.8 on 2023-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('user', '0002_userknownanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserKnownWord',
            new_name='UserUnknownWord',
        ),
        migrations.RenameField(
            model_name='userunknownword',
            old_name='date_learned',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='known_words',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unknown_words',
            field=models.ManyToManyField(through='user.UserUnknownWord', to='study.word'),
        ),
    ]
