# Generated by Django 4.2.8 on 2023-12-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_dictionary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dictionary',
            new_name='flashcard_dict',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picsu_dict',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
